name: Get Windsor-Essex Prices in csv

on:
  workflow_dispatch:

jobs:
  generate_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        persist-credentials: false
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Purge Chrome
      run: sudo apt purge google-chrome-stable  
  
    - name: Install packages
      run: pip install selenium beautifulsoup4 pandas pyvirtualdisplay
      
    - name: Install xvfb
      run: sudo apt-get install xvfb
      
    - name: Run script
      run: python "Windsor-Essex Gas Price by Station.py"

    - name: Commit changes
      run: |
        git config user.email "shithi30@gmail.com"
        git config user.name "shithi30"
        git add "Today's Fuel Prices.csv"
        git commit -m "Updated from yml"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITPAT_TOKEN }}
