name: Generate File and Commit to Repo

on:
  workflow_dispatch:

jobs:
  generate_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run Python script
      run: python "scrape_gas_price.py"

    - name: Commit changes
      run: |
        git config --global user.email "shithi30@gmail.com"
        git config --global user.name "shithi30"
        git add "Gas Price Data.txt"
        git commit -m "Updated from yml"

    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ secrets.GIT_PAT_TOKEN }}
