name: Generate File and Commit to Repo

on:
  workflow_dispatch:

jobs:
  generate_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run Python script
      run: python "scrape_gas_price.py"

    - name: Commit changes
      run: |
        git config user.name "shithi30"
        git config user.email "shithi30@gmail.com"
        git add "Gas Price Data.txt"
        git commit -m "Updated from yml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
