name: Test Workflow

on:
  push:
    branches:
      - main  # Specify the branch where commits trigger the workflow (e.g., main or any branch).
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run Python script
      run: python "test_script.py"
